version: '3.1'

services:
  siriuspacsdb:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
        - ./database/data/:/var/lib/mysql
        - ./database/entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - 0.0.0.0:33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: siriuspacsroot
      MYSQL_DATABASE: siriuspacsdb
      MYSQL_USER: siriuspacs
      MYSQL_PASSWORD: siriuspacs
